import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    home: 'Home',
    cars: 'Cars',
    about: 'About',
    contact: 'Contact',
    login: 'Login',
    register: 'Register',
    dashboard: 'Dashboard',
    logout: 'Logout',
    heroTitle: 'Premium Car Rental in Tirana',
    heroSubtitle: 'Discover Albania with our modern fleet of vehicles. Best prices, excellent service, and 24/7 support.',
    bookNow: 'Book Now',
    browseFleet: 'Browse Our Fleet',
    learnMore: 'Learn More',
    whyChooseUs: 'Why Choose MEMA Rental?',
    homeWhyTitle: 'Why Choose MEMA Rental for Car Rental in Tirana?',
    homeWhyCopy: 'We provide the best car rental experience in Tirana, Albania with competitive rates, reliable vehicles, and exceptional customer service. Your trusted car rental partner in Albania.',
    modernFleet: 'Modern Fleet',
    modernFleetDesc: 'Latest model vehicles with full insurance coverage',
    bestPrices: 'Best Prices',
    bestPricesDesc: 'Competitive rates with no hidden fees',
    support247: '24/7 Support',
    fullyInsured: '100% Insured',
    benefitFullyInsuredDesc: 'Comprehensive coverage for peace of mind',
    averageRating: '4.8 Rating',
    vehiclesCount: '6+ Vehicles',
    support247Desc: 'Round-the-clock customer assistance',
    benefitQuickBookingTitle: 'Quick Booking',
    benefitQuickBookingDesc: 'Reserve your car in minutes',
    benefitBestRatesTitle: 'Best Rates',
    benefitBestRatesDesc: 'Competitive pricing guaranteed',
    benefitFreeGpsTitle: 'Free GPS',
    benefitFreeGpsDesc: 'Navigation included with every rental',
    benefitFlexiblePaymentTitle: 'Flexible Payment',
    benefitFlexiblePaymentDesc: 'Multiple payment options accepted',
    availableCars: 'Available Cars',
    filterByBrand: 'Filter by Brand',
    allBrands: 'All Brands',
    priceRange: 'Price Range',
    automatic: 'Automatic',
    manual: 'Manual',
    seats: 'seats',
    luggage: 'luggage',
    perDay: 'per day',
    bookThisCar: 'Book This Car',
    pickupDate: 'Pickup Date',
    dropoffDate: 'Dropoff Date',
    pickupTime: 'Pickup Time',
    dropoffTime: 'Dropoff Time',
    location: 'Location',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    totalCost: 'Total Cost',
    confirmBooking: 'Confirm Booking',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    adminDashboard: 'Admin Dashboard',
    manageBookings: 'Manage Bookings',
    manageCars: 'Manage Cars',
    analytics: 'Analytics',
    users: 'Users',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    search: 'Search',
    locations: 'Locations',
    filter: 'Filter',
    status: 'Status',
    available: 'Available',
    booked: 'Booked',
    maintenance: 'Under Maintenance',
    footerDescription: 'Your trusted partner for car rentals in Tirana, Albania. Quality service and competitive prices.',
    quickLinks: 'Quick Links',
    navigation: 'Navigation',
    quickActions: 'Quick Actions',
    language: 'Language',
    adminPanel: 'Admin Panel',
    contactUs: 'Contact Us',
    followUs: 'Follow Us',
    ourStory: 'Our Story',
    ourMission: 'Our Mission',
    meetTheTeam: 'Meet The Team',
    getInTouch: 'Get In Touch',
    sendMessage: 'Send Message',
    message: 'Message',
    ourLocation: 'Our Location',
    homeDestinationsTitle: 'Popular Destinations in Albania',
    homeDestinationsCopy: 'Explore the best of Albania with our reliable car rental service from Tirana',
    destTiranaCenterName: 'Tirana City Center',
    destTiranaCenterDesc: 'Explore the capital of Albania',
    destDurresBeachName: 'Durres Beach',
    destDurresBeachDesc: 'Coastal adventures in Albania',
    destAlbanianAlpsName: 'Albanian Alps',
    destAlbanianAlpsDesc: 'Mountain escapes in Albania',
    destHistoricalSitesName: 'Historical Sites',
    destHistoricalSitesDesc: 'Cultural heritage of Albania',
    homeCtaTitle: 'Ready to Explore Albania?',
    homeCtaCopy: 'Book your car rental in Tirana today and start your Albanian adventure with the best rates and service. Available for pickup in Tirana city center and airport.',
    navExplore: 'Explore our services',
    navLearnAbout: 'Learn about',
    navBrowseFleet: 'Browse our fleet',
    navGetInTouch: 'Get in touch',
    quickSearchCars: 'Search Cars',
    rating: 'Rating',
    aboutHeroTitle: 'About MEMA Rental - Car Rental in Tirana, Albania',
    seoAboutTitle: 'About MEMA Rental - Car Rental Service in Tirana, Albania',
    seoAboutDescription: 'Learn about MEMA Rental, the leading car rental service in Tirana, Albania. Our story and commitment to providing the best car rental experience in Albania since 2014.',
    aboutHeroTitle: 'About MEMA Rental - Car Rental in Tirana, Albania',
    aboutHeroSubtitle: 'Your trusted partner for car rental in Tirana, Albania since 2014. We provide reliable, affordable, and convenient car rental services to help you explore the beauty of Albania. Located in the heart of Tirana city center.',
    aboutStoryTitle: 'Our Story - Car Rental in Tirana',
    aboutStoryP1: 'Founded in 2014, MEMA Rental began with a simple mission: to provide reliable and affordable car rental services in Tirana, Albania. What started as a small family business has grown into one of the most trusted car rental companies in the region.',
    aboutStoryP2: "We understand that exploring Albania requires more than just a vehicle - it requires a partner you can trust. That's why we've built our business on the principles of reliability, transparency, and exceptional customer service. Our commitment to providing the best car rental experience in Tirana has made us a preferred choice for both locals and tourists.",
    aboutStoryP3: "Today, we're proud to serve thousands of customers each year, helping them discover the beauty of Albania with our modern fleet of vehicles and dedicated support team. Our location in Tirana city center makes us easily accessible for all your car rental needs in Albania.",
    aboutWhyTitle: 'Why Choose MEMA Rental for Car Rental in Tirana?',
    aboutWhyCopy: 'We provide the best car rental experience in Tirana, Albania with competitive rates, reliable vehicles, and exceptional customer service. Your trusted car rental partner in Albania.',
    statsVehicles: 'Vehicles',
    statsHappyCustomers: 'Happy Customers',
    statsRating: 'Rating',
    statsYears: 'Years',
    contactInfoTitle: 'Contact Information - Car Rental Tirana',
    contactInfoCopy: "Get in touch with us for any questions about car rental in Tirana, Albania. We're located in the heart of Tirana city center for your convenience.",
    contactLocation: 'Location',
    contactCityCenter: 'City Center Location',
    contactPhone: 'Phone',
    contactSupport: '24/7 Support Available',
    contactEmail: 'Email',
    contactQuickResponse: 'Quick Response Guaranteed',
    wantToGetInTouch: 'Want to get in touch?',
    contactUsHere: 'Contact us here',
    carsHeroTitle: 'Car Rental Fleet in Tirana, Albania',
    carsHeroSubtitle: 'Browse our complete selection of rental cars in Tirana. From economy to luxury vehicles, find the perfect car for your Albanian adventure. All vehicles are well-maintained and come with comprehensive insurance. Located in the heart of Tirana city center.',
    contactHeroTitle: 'Get in Touch',
    contactHeroSubtitle: "Ready to explore Albania? Contact us for the best car rental experience in Tirana. We're here to help you with your transportation needs.",
    carDetailHeroSubtitle: 'Premium features, superior comfort, and outstanding performance. Book now for your Tirana journey.',
    bookingHeroTitle: 'Book Your Car Rental in Tirana, Albania',
    bookingHeroSubtitle: 'Complete your booking for the {brand} {model} - Best car rental service in Tirana',
    seoHomeTitle: 'Car Rental Tirana Albania | Best Car Hire Service in Tirana',
    seoHomeDescription: 'Best car rental in Tirana, Albania. Rent cars, SUVs, and luxury vehicles from €25/day. Free pickup, 24/7 support, and competitive rates. Book your car rental in Albania today! Located in Tirana city center.',
    seoCarsTitle: 'Car Rental Fleet Tirana Albania | Best Car Hire Service in Tirana',
    seoCarsDescription: 'Browse our complete car rental fleet in Tirana, Albania. Rent BMW, Mercedes, Audi, Toyota, Volkswagen, and Ford vehicles from €38/day. Best car hire selection in Albania. Located in Tirana city center.',
    carsHeroTitle: 'Car Rental Fleet in Tirana, Albania',
    carsHeroSubtitle: 'Browse our complete selection of rental cars in Tirana. From economy to luxury vehicles, find the perfect car for your Albanian adventure. All vehicles are well-maintained and come with comprehensive insurance. Located in the heart of Tirana city center.',
    carsSearchPlaceholder: 'Search cars by brand or model for rent in Tirana...',
    carsAvailableCount: '{count} car{plural} available for rent in Tirana, Albania',
    filters: 'Filters',
    brand: 'Brand',
    allBrands: 'All brands',
    category: 'Category',
    allCategories: 'All categories',
    priceRangeLabel: 'Price Range',
    allPrices: 'All prices',
    under50: 'Under €50/day',
    between50And70: '€50-€70/day',
    over70: 'Over €70/day',
    clear: 'Clear',
    notAvailable: 'Not Available',
    year: 'Year',
    location: 'Location',
    more: 'more',
    perDay: 'per day',
    rentThisCar: 'Rent This Car',
    insured: 'Insured',
    noCarsFound: 'No cars found',
    tryAdjusting: 'Try adjusting your search criteria or contact us for custom car rental requests in Tirana.',
    clearAllFilters: 'Clear All Filters',
    infoTitle: 'Car Rental Information - Tirana, Albania',
    infoReqs: 'Car Rental Requirements in Tirana',
    req1: "Valid driver's license (minimum 1 year)",
    req2: 'Passport or ID card',
    req3: 'Credit card for deposit',
    req4: 'Minimum age: 21 years',
    req5: 'International driving permit recommended',
    infoServices: 'Car Rental Services in Albania',
    serv1: 'Free pickup and delivery in Tirana',
    serv2: '24/7 roadside assistance',
    serv3: 'Comprehensive insurance coverage',
    serv4: 'GPS navigation available',
    serv5: 'Child seats available',
    seoContactTitle: 'Contact MEMA Rental - Car Rental Service in Tirana, Albania | Get in Touch',
    seoContactDescription: 'Contact MEMA Rental for car rental services in Tirana, Albania. Get in touch for bookings, support, or inquiries. Located in Tirana city center.',
    contactHeroTitle: 'Get in Touch',
    contactHeroSubtitle: "Ready to explore Albania? Contact us for the best car rental experience in Tirana. We're here to help you with your transportation needs.",
    contactHeaderTitle: 'Get in Touch',
    contactHeaderCopy: "Ready to explore Albania? Contact us for the best car rental experience in Tirana. We're here to help you with your transportation needs.",
    contactInfo: 'Contact Information',
    visitUs: 'Visit Us',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    businessHours: 'Business Hours',
    cityCenterLocation: 'City Center Location',
    supportAvailable: '24/7 Support Available',
    quickResponse: 'Quick Response Guaranteed',
    hoursValue: 'Mon-Sun: 8:00 AM - 8:00 PM',
    sendUsMessage: 'Send us a Message',
    sendFormCopy: "Fill out the form below and we'll get back to you as soon as possible.",
    fullNameReq: 'Full Name *',
    emailAddressReq: 'Email Address *',
    phoneNumber: 'Phone Number',
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email address',
    enterPhone: 'Enter your phone number',
    subjectReq: 'Subject *',
    selectSubject: 'Select a subject',
    subjBooking: 'Car Rental Booking',
    subjSupport: 'Technical Support',
    subjInquiry: 'General Inquiry',
    subjFeedback: 'Feedback',
    subjOther: 'Other',
    messageReq: 'Message *',
    messagePlaceholder: 'Tell us how we can help you with car rental in Tirana, Albania...',
    sendingMessage: 'Sending Message...',
    sendMessage: 'Send Message',
    findUsTitle: 'Find Us - Car Rental Tirana',
    interactiveMapSoon: 'Interactive map coming soon',
    carRentalRequirements: 'Car Rental Requirements',
    requirementsInTirana: 'Requirements in Tirana',
    backToCars: 'Back to Cars',
    ratingLabel: 'Rating',
    seatsLabel: 'Seats',
    insured: 'Insured',
    description: 'Description',
    features: 'Features',
    specifications: 'Specifications',
    pickupLocation: 'Pickup Location',
    pickupTimeLabel: 'Pickup Time',
    flexibleScheduling: 'Flexible scheduling',
    bookThisCar: 'Book This Car',
    contactUs: 'Contact Us',
    pricePerDay: '{price}/day',
    carDetailHeaderSuffix: ' - Car Rental in Tirana',
    whyChooseMema: 'Why Choose MEMA Rental for Car Rental in Tirana?',
    seoBookingTitle: 'Book Car Rental in Tirana, Albania - {brand} {model}',
    seoBookingDesc: 'Book your {brand} {model} rental in Tirana, Albania. Secure online booking with instant confirmation. Best car rental service in Tirana with competitive rates.',
    bookingHeroTitle: 'Book Your Car Rental in Tirana, Albania',
    bookingHeroSubtitleFmt: 'Complete your booking for the {brand} {model} - Best car rental service in Tirana',
    bookingHeaderTitle: 'Book Your Car Rental in Tirana, Albania',
    bookingHeaderCopyFmt: 'Complete your booking for the {brand} {model} - Best car rental service in Tirana',
    bookingDetails: 'Booking Details - Car Rental in Tirana',
    step1Title: 'Select Dates & Times',
    pickupDate: 'Pickup Date',
    returnDate: 'Return Date',
    pickupTime: 'Pickup Time',
    returnTime: 'Return Time',
    selectPickupTime: 'Select pickup time',
    selectReturnTime: 'Select return time',
    step2Title: 'Personal Details',
    firstName: 'First Name',
    lastName: 'Last Name',
    driversLicenseNumber: "Driver's License Number",
    licenseExpiry: 'License Expiry Date',
    step3Title: 'Extras & Location',
    pickupLocationLabel: 'Pickup Location',
    returnLocationLabel: 'Return Location',
    selectPickupLocation: 'Select pickup location',
    selectReturnLocation: 'Select return location',
    additionalServices: 'Additional Services',
    perDayLower: '/day',
    specialRequests: 'Special Requests',
    specialRequestsPlaceholder: 'Any special requests or requirements...',
    step4Title: 'Payment Information',
    cardNumber: 'Card Number',
    cardholderName: 'Cardholder Name',
    expiryDate: 'Expiry Date',
    cvc: 'CVC',
    acceptTerms: 'I accept the terms and conditions and privacy policy',
    back: 'Back',
    next: 'Next',
    completeBooking: 'Complete Booking',
    carSummary: 'Car Summary',
    seatsLower: 'seats',
    bookingSummary: 'Booking Summary',
    rentalPeriod: 'Rental Period:',
    daysLower: 'days',
    basePrice: 'Base Price:',
    extrasLabel: 'Extras:',
    total: 'Total:',
    whyChooseMemaShort: 'Why Choose MEMA Rental?',
    needHelp: 'Need Help?',
  },
  sq: {
    home: 'Kryefaqja',
    cars: 'Makinat',
    about: 'Rreth Nesh',
    contact: 'Na Kontaktoni',
    login: 'Hyrje',
    register: 'Regjistrohu',
    dashboard: 'Paneli',
    logout: 'Dalje',
    heroTitle: 'Qera Makinash Premium në Tiranë',
    heroSubtitle: 'Zbuloni Shqipërinë me flotën tonë moderne të automjeteve. Çmimet më të mira, shërbim i shkëlqyer dhe mbështetje 24/7.',
    bookNow: 'Rezervo Tani',
    browseFleet: 'Shfleto Flotën',
    learnMore: 'Mëso Më Shumë',
    whyChooseUs: 'Pse të Zgjidhni MEMA Rental?',
    homeWhyTitle: 'Pse të zgjidhni MEMA Rental për makinë me qera në Tiranë?',
    homeWhyCopy: 'Ofruajmë përvojën më të mirë të qerasë së makinave në Tiranë me çmime konkurruese, automjete të besueshme dhe shërbim të shkëlqyer ndaj klientit. Partneri juaj i besuar për qera makinash në Shqipëri.',
    modernFleet: 'Flotë Moderne',
    modernFleetDesc: 'Automjete të modeleve të fundit me mbulim të plotë sigurie',
    bestPrices: 'Çmimet Më të Mira',
    bestPricesDesc: 'Tarifa konkurruese pa tarifa të fshehura',
    support247: 'Mbështetje 24/7',
    fullyInsured: '100% e Siguruar',
    benefitFullyInsuredDesc: 'Mbulim i plotë sigurie për qetësi mendore',
    averageRating: 'Vlerësim 4.8',
    vehiclesCount: '6+ Mjete',
    support247Desc: 'Asistencë e klientit gjatë gjithë kohës',
    benefitQuickBookingTitle: 'Rezervim i Shpejtë',
    benefitQuickBookingDesc: 'Rezervoni makinën në pak minuta',
    benefitBestRatesTitle: 'Çmimet më të mira',
    benefitBestRatesDesc: 'Çmime konkurruese të garantuara',
    benefitFreeGpsTitle: 'GPS Falas',
    benefitFreeGpsDesc: 'Navigim i përfshirë me çdo qera',
    benefitFlexiblePaymentTitle: 'Pagesë Fleksibile',
    benefitFlexiblePaymentDesc: 'Pranohen disa mënyra pagese',
    availableCars: 'Makinat e Disponueshme',
    filterByBrand: 'Filtro sipas Markës',
    allBrands: 'Të Gjitha Markat',
    priceRange: 'Intervali i Çmimit',
    automatic: 'Automatike',
    manual: 'Manuale',
    seats: 'ulëse',
    luggage: 'bagazh',
    perDay: 'në ditë',
    bookThisCar: 'Rezervo Këtë Makinë',
    pickupDate: 'Data e Marrjes',
    dropoffDate: 'Data e Kthimit',
    pickupTime: 'Ora e Marrjes',
    dropoffTime: 'Ora e Kthimit',
    location: 'Vendndodhja',
    fullName: 'Emri i Plotë',
    email: 'Email',
    phone: 'Telefoni',
    totalCost: 'Kostoja Totale',
    confirmBooking: 'Konfirmo Rezervimin',
    signIn: 'Hyrje',
    signUp: 'Regjistrohu',
    password: 'Fjalëkalimi',
    confirmPassword: 'Konfirmo Fjalëkalimin',
    adminDashboard: 'Paneli i Administratorit',
    manageBookings: 'Menaxho Rezervimet',
    manageCars: 'Menaxho Makinat',
    analytics: 'Analitika',
    users: 'Përdoruesit',
    loading: 'Duke ngarkuar...',
    save: 'Ruaj',
    cancel: 'Anulo',
    edit: 'Ndrysho',
    delete: 'Fshi',
    add: 'Shto',
    search: 'Kërko',
    locations: 'Vendndodhjet',
    filter: 'Filtro',
    status: 'Statusi',
    available: 'I Disponueshëm',
    booked: 'I Rezervuar',
    maintenance: 'Në Mirëmbajtje',
    footerDescription: 'Partneri juaj i besuar për makina me qera në Tiranë, Shqipëri. Shërbim cilësor dhe çmime konkurruese.',
    quickLinks: 'Linqe të Shpejta',
    contactUs: 'Na Kontaktoni',
    followUs: 'Na Ndiqni',
    ourStory: 'Historia Jonë',
    ourMission: 'Misioni Ynë',
    meetTheTeam: 'Njihuni me Ekipin',
    getInTouch: 'Na Kontaktoni',
    sendMessage: 'Dërgo Mesazh',
    message: 'Mesazhi',
    ourLocation: 'Vendndodhja Jonë',
    homeDestinationsTitle: 'Destinacionet Popullore në Shqipëri',
    homeDestinationsCopy: 'Zbuloni më të mirat e Shqipërisë me shërbimin tonë të besueshëm të qerasë nga Tirana',
    destTiranaCenterName: 'Qendra e Tiranës',
    destTiranaCenterDesc: 'Eksploroni kryeqytetin e Shqipërisë',
    destDurresBeachName: 'Plazhi i Durrësit',
    destDurresBeachDesc: 'Aventura bregdetare në Shqipëri',
    destAlbanianAlpsName: 'Alpet Shqiptare',
    destAlbanianAlpsDesc: 'Arratisje malore në Shqipëri',
    destHistoricalSitesName: 'Sitet Historike',
    destHistoricalSitesDesc: 'Trashëgimia kulturore e Shqipërisë',
    homeCtaTitle: 'Gati për të eksploruar Shqipërinë?',
    homeCtaCopy: 'Rezervoni sot makinën tuaj me qera në Tiranë dhe nisni aventurën shqiptare me çmimet dhe shërbimin më të mirë. E disponueshme për marrje në qendër të Tiranës dhe në aeroport.',
    navExplore: 'Zbuloni shërbimet tona',
    navLearnAbout: 'Mësoni rreth',
    navBrowseFleet: 'Shfletoni flotën',
    navGetInTouch: 'Na kontaktoni',
    quickSearchCars: 'Kërko Makinat',
    rating: 'Vlerësim',
    aboutHeroTitle: 'Rreth MEMA Rental - Makina me qera në Tiranë, Shqipëri',
    seoAboutTitle: 'Rreth MEMA Rental - Shërbimi i makinave me qera në Tiranë, Shqipëri',
    seoAboutDescription: 'Mësoni rreth MEMA Rental, shërbimit kryesor të makinave me qera në Tiranë, Shqipëri. Historia jonë dhe angazhimi për të ofruar përvojën më të mirë që prej vitit 2014.',
    aboutHeroTitle: 'Rreth MEMA Rental - Makina me qera në Tiranë, Shqipëri',
    aboutHeroSubtitle: 'Partneri juaj i besuar për qera makinash në Tiranë që nga 2014. Ofron shërbime të besueshme, të përballueshme dhe të përshtatshme për të eksploruar Shqipërinë. I vendosur në qendër të Tiranës.',
    aboutStoryTitle: 'Historia jonë - Makina me qera në Tiranë',
    aboutStoryP1: 'E themeluar në vitin 2014, MEMA Rental nisi me një mision të thjeshtë: të ofrojë shërbime të besueshme dhe të përballueshme të qerasë së makinave në Tiranë, Shqipëri. Ajo që filloi si një biznes familjar i vogël është shndërruar në një nga kompanitë më të besuara në rajon.',
    aboutStoryP2: 'E kuptojmë që eksplorimi i Shqipërisë kërkon më shumë se një automjet — kërkon një partner të besueshëm. Prandaj e kemi ndërtuar biznesin mbi parimet e besueshmërisë, transparencës dhe shërbimit të jashtëzakonshëm ndaj klientit. Angazhimi ynë për të ofruar përvojën më të mirë të qerasë në Tiranë na ka bërë zgjedhjen e preferuar për vendas dhe turistë.',
    aboutStoryP3: 'Sot jemi krenarë që u shërbejmë mijëra klientëve çdo vit, duke i ndihmuar të zbulojnë bukuritë e Shqipërisë me flotën tonë moderne dhe ekipin e përkushtuar. Vendndodhja jonë në qendër të Tiranës na bën lehtësisht të aksesueshëm për të gjitha nevojat tuaja për qera makinash.',
    aboutWhyTitle: 'Pse të zgjidhni MEMA Rental për makinë me qera në Tiranë?',
    aboutWhyCopy: 'Ofruajmë përvojën më të mirë të qerasë së makinave në Tiranë me çmime konkurruese, automjete të besueshme dhe shërbim të shkëlqyer. Partneri juaj i besuar në Shqipëri.',
    statsVehicles: 'Mjete',
    statsHappyCustomers: 'Klientë të Kënaqur',
    statsRating: 'Vlerësim',
    statsYears: 'Vite',
    contactInfoTitle: 'Informacione Kontakti - Qera Makinash Tiranë',
    contactInfoCopy: 'Na kontaktoni për çdo pyetje rreth qerasë së makinave në Tiranë. Ndodhemi në qendër të Tiranës për komoditetin tuaj.',
    contactLocation: 'Vendndodhja',
    contactCityCenter: 'Vendndodhje në Qendër të Qytetit',
    contactPhone: 'Telefoni',
    contactSupport: 'Mbështetje 24/7',
    contactEmail: 'Email',
    contactQuickResponse: 'Përgjigje e Shpejtë e Garantuar',
    wantToGetInTouch: 'Dëshironi të na kontaktoni?',
    contactUsHere: 'Na kontaktoni këtu',
    carsHeroTitle: 'Flota e makinave me qera në Tiranë, Shqipëri',
    carsHeroSubtitle: 'Shfletoni përzgjedhjen tonë të plotë të makinave me qera në Tiranë. Nga ekonomike te luksoze, gjeni makinën perfekte për aventurën tuaj. Të gjitha mjetet janë të mirëmbajtura dhe me sigurim të plotë.',
    contactHeroTitle: 'Na Kontaktoni',
    contactHeroSubtitle: 'Gati për të eksploruar Shqipërinë? Na kontaktoni për përvojën më të mirë të qerasë së makinave në Tiranë. Jemi këtu për t’ju ndihmuar.',
    carDetailHeroSubtitle: 'Veçori premium, rehati superiore dhe performancë e shkëlqyer. Rezervoni tani për udhëtimin tuaj në Tiranë.',
    bookingHeroTitle: 'Rezervoni makinën tuaj me qera në Tiranë, Shqipëri',
    bookingHeroSubtitle: 'Plotësoni rezervimin për {brand} {model} - Shërbimi më i mirë i qerasë në Tiranë',
    seoHomeTitle: 'Qera Makinash në Tiranë, Shqipëri | Shërbimi më i mirë i qerasë në Tiranë',
    seoHomeDescription: 'Qera makinash në Tiranë, Shqipëri. Merrni makina, SUV dhe automjete luksoze nga €25/ditë. Marrje falas, mbështetje 24/7 dhe çmime konkurruese. Rezervoni sot! Vendndodhje në qendër të Tiranës.',
    seoCarsTitle: 'Flota e makinave me qera në Tiranë | Shërbimi më i mirë i qerasë',
    seoCarsDescription: 'Shfletoni flotën tonë të plotë të makinave me qera në Tiranë. Merrni BMW, Mercedes, Audi, Toyota, Volkswagen dhe Ford nga €38/ditë. Përzgjedhja më e mirë në Shqipëri. Në qendër të Tiranës.',
    carsHeroTitle: 'Flota e makinave me qera në Tiranë, Shqipëri',
    carsHeroSubtitle: 'Shfletoni përzgjedhjen e plotë të makinave me qera në Tiranë. Nga ekonomike te luksoze, gjeni makinën perfekte për aventurën tuaj. Të gjitha mjetet janë të mirëmbajtura dhe me sigurim të plotë. Vendndodhje në qendër të Tiranës.',
    carsSearchPlaceholder: 'Kërko makina sipas markës ose modelit për qera në Tiranë...',
    carsAvailableCount: '{count} makinë{plural} të disponueshme për qera në Tiranë, Shqipëri',
    filters: 'Filtrat',
    brand: 'Marka',
    allBrands: 'Të gjitha markat',
    category: 'Kategoria',
    allCategories: 'Të gjitha kategoritë',
    priceRangeLabel: 'Intervali i Çmimit',
    allPrices: 'Të gjitha çmimet',
    under50: 'Nën €50/ditë',
    between50And70: '€50-€70/ditë',
    over70: 'Mbi €70/ditë',
    clear: 'Pastro',
    notAvailable: 'Jo e Disponueshme',
    year: 'Viti',
    location: 'Vendndodhja',
    more: 'të tjera',
    perDay: 'në ditë',
    rentThisCar: 'Rezervo Këtë Makinë',
    insured: 'E Siguruar',
    noCarsFound: 'Asnjë makinë nuk u gjet',
    tryAdjusting: 'Provoni të ndryshoni kriteret ose na kontaktoni për kërkesa të personalizuara në Tiranë.',
    clearAllFilters: 'Pastro të Gjitha Filtrat',
    infoTitle: 'Informacione për Qeranë e Makinave - Tiranë, Shqipëri',
    infoReqs: 'Kërkesat për Qerim në Tiranë',
    req1: 'Leje drejtimi e vlefshme (minimumi 1 vit)',
    req2: 'Pasaportë ose kartë ID',
    req3: 'Kartë krediti për garanci',
    req4: 'Mosha minimale: 21 vjeç',
    req5: 'Rekomandohet leje ndërkombëtare drejtimi',
    infoServices: 'Shërbime Qeraje në Shqipëri',
    serv1: 'Marrje dhe dorëzim falas në Tiranë',
    serv2: 'Asistencë rrugore 24/7',
    serv3: 'Mbulim i plotë sigurimi',
    serv4: 'GPS i disponueshëm',
    serv5: 'Sende për fëmijë të disponueshme',
    seoContactTitle: 'Na Kontaktoni - Shërbimi i makinave me qera në Tiranë | Na kontaktoni',
    seoContactDescription: 'Na kontaktoni për shërbime qeraje makinash në Tiranë. Për rezervime, mbështetje ose pyetje. Vendndodhje në qendër të Tiranës.',
    contactHeroTitle: 'Na Kontaktoni',
    contactHeroSubtitle: 'Gati për të eksploruar Shqipërinë? Na kontaktoni për përvojën më të mirë të qerasë në Tiranë. Jemi këtu për t’ju ndihmuar.',
    contactHeaderTitle: 'Na Kontaktoni',
    contactHeaderCopy: 'Gati për të eksploruar Shqipërinë? Na kontaktoni për përvojën më të mirë të qerasë në Tiranë. Jemi këtu për t’ju ndihmuar.',
    contactInfo: 'Informacione Kontakti',
    visitUs: 'Na Vizitoni',
    callUs: 'Na Telefononi',
    emailUs: 'Na dërgoni Email',
    businessHours: 'Orari i Punës',
    cityCenterLocation: 'Vendndodhje në Qendër të Qytetit',
    supportAvailable: 'Mbështetje 24/7',
    quickResponse: 'Përgjigje e Shpejtë e Garantuar',
    hoursValue: 'Hën-Diel: 08:00 - 20:00',
    sendUsMessage: 'Na dërgoni një Mesazh',
    sendFormCopy: 'Plotësoni formularin më poshtë dhe do t’ju kontaktojmë sa më shpejt.',
    fullNameReq: 'Emri i Plotë *',
    emailAddressReq: 'Adresa Email *',
    phoneNumber: 'Numri i Telefonit',
    enterFullName: 'Shkruani emrin e plotë',
    enterEmail: 'Shkruani adresën tuaj email',
    enterPhone: 'Shkruani numrin e telefonit',
    subjectReq: 'Subjekti *',
    selectSubject: 'Zgjidhni një subjekt',
    subjBooking: 'Rezervim Qeraje Makine',
    subjSupport: 'Mbështetje Teknike',
    subjInquiry: 'Pyetje të Përgjithshme',
    subjFeedback: 'Përshtypje',
    subjOther: 'Tjetër',
    messageReq: 'Mesazhi *',
    messagePlaceholder: 'Na tregoni si mund t’ju ndihmojmë me qeranë e makinës në Tiranë, Shqipëri...',
    sendingMessage: 'Duke dërguar mesazhin...',
    sendMessage: 'Dërgo Mesazhin',
    findUsTitle: 'Na Gjeni - Qera Makinash Tiranë',
    interactiveMapSoon: 'Harta interaktive së shpejti',
    carRentalRequirements: 'Kërkesat për Qeranë e Makinave',
    requirementsInTirana: 'Kërkesat në Tiranë',
    backToCars: 'Kthehu te Makinat',
    ratingLabel: 'Vlerësim',
    seatsLabel: 'Ulëse',
    insured: 'E Siguruar',
    description: 'Përshkrimi',
    features: 'Veçoritë',
    specifications: 'Specifikimet',
    pickupLocation: 'Vendndodhja e Marrjes',
    pickupTimeLabel: 'Koha e Marrjes',
    flexibleScheduling: 'Orar fleksibël',
    bookThisCar: 'Rezervo Këtë Makinë',
    contactUs: 'Na Kontaktoni',
    pricePerDay: '{price}/ditë',
    carDetailHeaderSuffix: ' - Makina me qera në Tiranë',
    whyChooseMema: 'Pse të zgjidhni MEMA Rental për makinë me qera në Tiranë?',
    seoBookingTitle: 'Rezervo makinë me qera në Tiranë, Shqipëri - {brand} {model}',
    seoBookingDesc: 'Rezervoni {brand} {model} në Tiranë. Rezervim online i sigurt me konfirmim të menjëhershëm. Shërbimi më i mirë me çmime konkurruese.',
    bookingHeroTitle: 'Rezervo makinën tënde me qera në Tiranë, Shqipëri',
    bookingHeroSubtitleFmt: 'Përfundoni rezervimin për {brand} {model} - Shërbimi më i mirë në Tiranë',
    bookingHeaderTitle: 'Rezervo makinën tënde me qera në Tiranë, Shqipëri',
    bookingHeaderCopyFmt: 'Përfundoni rezervimin për {brand} {model} - Shërbimi më i mirë në Tiranë',
    bookingDetails: 'Detajet e Rezervimit - Qera Makinash në Tiranë',
    step1Title: 'Zgjidhni Datat dhe Orët',
    pickupDate: 'Data e Marrjes',
    returnDate: 'Data e Kthimit',
    pickupTime: 'Ora e Marrjes',
    returnTime: 'Ora e Kthimit',
    selectPickupTime: 'Zgjidhni orën e marrjes',
    selectReturnTime: 'Zgjidhni orën e kthimit',
    step2Title: 'Të Dhënat Personale',
    firstName: 'Emri',
    lastName: 'Mbiemri',
    driversLicenseNumber: 'Numri i Lejes së Drejtimit',
    licenseExpiry: 'Data e Skadencës së Lejes',
    step3Title: 'Shtesa & Vendndodhja',
    pickupLocationLabel: 'Vendndodhja e Marrjes',
    returnLocationLabel: 'Vendndodhja e Kthimit',
    selectPickupLocation: 'Zgjidhni vendndodhjen e marrjes',
    selectReturnLocation: 'Zgjidhni vendndodhjen e kthimit',
    additionalServices: 'Shërbime Shtesë',
    perDayLower: '/ditë',
    specialRequests: 'Kërkesa të Veçanta',
    specialRequestsPlaceholder: 'Ndoni kërkesa të veçanta ose nevoja...',
    step4Title: 'Informacioni i Pagesës',
    cardNumber: 'Numri i Kartës',
    cardholderName: 'Emri në Kartë',
    expiryDate: 'Data e Skadencës',
    cvc: 'CVC',
    acceptTerms: 'Pranoj kushtet e përdorimit dhe politikën e privatësisë',
    back: 'Prapa',
    next: 'Vazhdo',
    completeBooking: 'Përfundo Rezervimin',
    carSummary: 'Përmbledhje e Makinës',
    seatsLower: 'ulëse',
    bookingSummary: 'Përmbledhja e Rezervimit',
    rentalPeriod: 'Periudha e Qerasë:',
    daysLower: 'ditë',
    basePrice: 'Çmimi Bazë:',
    extrasLabel: 'Shtesa:',
    total: 'Totali:',
    whyChooseMemaShort: 'Pse MEMA Rental?',
    needHelp: 'Keni nevojë për ndihmë?',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => translations[language][key] || key;

  const tFormat = (key, vars = {}) => {
    const template = translations[language][key] || key;
    return template.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? String(vars[k]) : `{${k}}`));
  };

  const switchLanguage = (lang) => {
    setLanguage(lang);
  };

  const value = {
    language,
    t,
    tFormat,
    switchLanguage
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};